Rails:
  Enabled: true

AllCops:
  Exclude:
    - db/schema.rb
    - bin/*

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Bundler/OrderedGems:
  Enabled: false

Documentation:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false
